--[[
	© 2020 TERRANOVA do not share, re-distribute or modify
	without permission of its author.
--]]
Schema.voices.Add("Vortigaunt", "Accept Charge", "Accept the charge.", "vo/npc/vortigaunt/acceptcharge.wav")
Schema.voices.Add("Vortigaunt", "Accompany", "Gladly we accompany.", "vo/npc/vortigaunt/accompany.wav")
Schema.voices.Add("Vortigaunt", "Affirmed", "Affirmed.", "vo/npc/vortigaunt/affirmed.wav")
Schema.voices.Add("Vortigaunt", "All For Now", "That is all for now.", "vo/npc/vortigaunt/allfornow.wav")
Schema.voices.Add("Vortigaunt", "Allow Me", "Allow me.", "vo/npc/vortigaunt/allowme.wav")
Schema.voices.Add("Vortigaunt", "As You Wish", "As you wish.", "vo/npc/vortigaunt/asyouwish.wav")
Schema.voices.Add("Vortigaunt", "Believe The Opposite", "We believe the opposite.", "vo/npc/vortigaunt/vanswer03.wav")
Schema.voices.Add("Vortigaunt", "By Our Honor", "By our honor.", "vo/npc/vortigaunt/ourhonor.wav")
Schema.voices.Add("Vortigaunt", "Calm", "Caaaalm yourself.", "vo/npc/vortigaunt/calm.wav")
Schema.voices.Add("Vortigaunt", "Caution", "Caution!", "vo/npc/vortigaunt/caution.wav")
Schema.voices.Add("Vortigaunt", "Certainly", "Certainly.", "vo/npc/vortigaunt/certainly.wav")
Schema.voices.Add("Vortigaunt", "Concern", "Your concern is touching.", "vo/npc/vortigaunt/vanswer07.wav")
Schema.voices.Add("Vortigaunt", "Delay", "Is there reason for delay?", "vo/npc/vortigaunt/reasondelay.wav")
Schema.voices.Add("Vortigaunt", "Done", "Done.", "vo/npc/vortigaunt/done.wav")
Schema.voices.Add("Vortigaunt", "Dreamed", "We have dreamed of this moment.", "vo/npc/vortigaunt/dreamed.wav")
Schema.voices.Add("Vortigaunt", "Empower Us", "Empower us!", "vo/npc/vortigaunt/empowerus.wav")
Schema.voices.Add("Vortigaunt", "Expected", "We expected this much.", "vo/npc/vortigaunt/vanswer05.wav")
Schema.voices.Add("Vortigaunt", "Extract", "The extraaact.", "vo/outland_03_04/tunnels/vort_extract_theextract02.wav")
Schema.voices.Add("Vortigaunt", "Failed You", "We fear we have failed you.", "vo/npc/vortigaunt/fearfailed.wav")
Schema.voices.Add("Vortigaunt", "For Freedom", "For freedom!", "vo/npc/vortigaunt/forfreedom.wav")
Schema.voices.Add("Vortigaunt", "Forward", "Forward!", "vo/npc/vortigaunt/forward.wav")
Schema.voices.Add("Vortigaunt", "Gladly", "Gladly.", "vo/npc/vortigaunt/gladly.wav")
Schema.voices.Add("Vortigaunt", "Halt", "Halt.", "vo/npc/vortigaunt/halt.wav")
Schema.voices.Add("Vortigaunt", "Here", "Here.", "vo/npc/vortigaunt/here.wav")
Schema.voices.Add("Vortigaunt", "Hold", "Hold.", "vo/npc/vortigaunt/hold.wav")
Schema.voices.Add("Vortigaunt", "Hold Still", "Hold still.", "vo/npc/vortigaunt/holdstill.wav")
Schema.voices.Add("Vortigaunt", "Hope", "Hope is in sight.", "vo/npc/vortigaunt/vques03.wav")
Schema.voices.Add("Vortigaunt", "Hopeless", "Our cause seems hopeless.", "vo/npc/vortigaunt/hopeless.wav")
Schema.voices.Add("Vortigaunt", "Honor", "It is an honor.", "vo/npc/vortigaunt/itishonor.wav")
Schema.voices.Add("Vortigaunt", "Honored", "We are honored.", "vo/npc/vortigaunt/wehonored.wav")
Schema.voices.Add("Vortigaunt", "Honor Is Ours", "The honor is ours.", "vo/npc/vortigaunt/honorours.wav")
Schema.voices.Add("Vortigaunt", "Illusions", "You are not the first to harbor such illusions.", "vo/npc/vortigaunt/vanswer02.wav")
Schema.voices.Add("Vortigaunt", "Know You", "We know you.", "vo/npc/vortigaunt/weknowyou.wav")
Schema.voices.Add("Vortigaunt", "Lead On", "Lead on.", "vo/npc/vortigaunt/leadon.wav")
Schema.voices.Add("Vortigaunt", "Lead Us", "Lead us.", "vo/npc/vortigaunt/leadus.wav")
Schema.voices.Add("Vortigaunt", "Live To Serve", "We live to serve.", "vo/npc/vortigaunt/livetoserve.wav")
Schema.voices.Add("Vortigaunt", "Lost All Dear", "We have lost all dear to us.", "vo/npc/vortigaunt/alldear.wav")
Schema.voices.Add("Vortigaunt", "Mutual", "Our purpose is mutual.", "vo/npc/vortigaunt/mutual.wav")
Schema.voices.Add("Vortigaunt", "Mutual Feeling", "The feeling is mutual.", "vo/npc/vortigaunt/vanswer16.wav")
Schema.voices.Add("Vortigaunt", "Mystery", "We serve the same mystery.", "vo/npc/vortigaunt/mystery.wav")
Schema.voices.Add("Vortigaunt", "Onward", "Onward!", "vo/npc/vortigaunt/onward.wav")
Schema.voices.Add("Vortigaunt", "Opaque", "Your mind is opaque.", "vo/npc/vortigaunt/opaque.wav")
Schema.voices.Add("Vortigaunt", "Our Place", "Our place is here.", "vo/npc/vortigaunt/ourplacehere.wav")
Schema.voices.Add("Vortigaunt", "Pleasure", "With pleasure...", "vo/npc/vortigaunt/pleasure.wav")
Schema.voices.Add("Vortigaunt", "Prevail", "We shall prevail.", "vo/npc/vortigaunt/prevail.wav")
Schema.voices.Add("Vortigaunt", "Regrettable", "This is regrettable.", "vo/npc/vortigaunt/regrettable.wav")
Schema.voices.Add("Vortigaunt", "Stand Clear", "Stand clear!", "vo/npc/vortigaunt/standclear.wav")
Schema.voices.Add("Vortigaunt", "Still Here", "We are still here.", "vo/npc/vortigaunt/stillhere.wav")
Schema.voices.Add("Vortigaunt", "Survived 1", "We have survived darker times.", "vo/npc/vortigaunt/vques06.wav")
Schema.voices.Add("Vortigaunt", "Survived 2", "We have survived worse across the ages.", "vo/npc/vortigaunt/seenworse.wav")
Schema.voices.Add("Vortigaunt", "That Is All", "That is all.", "vo/npc/vortigaunt/thatisall.wav")
Schema.voices.Add("Vortigaunt", "This Body", "This body is yours to command.", "vo/npc/vortigaunt/bodyyours.wav")
Schema.voices.Add("Vortigaunt", "To The Void", "To the void with you!", "vo/npc/vortigaunt/tothevoid.wav")
Schema.voices.Add("Vortigaunt", "Trouble No More", "That one shall trouble us no more.", "vo/npc/vortigaunt/troubleus.wav")
Schema.voices.Add("Vortigaunt", "Turning Point", "This marks a turning point.", "vo/npc/vortigaunt/vques04.wav")
Schema.voices.Add("Vortigaunt", "Unconvinced", "We remain unconvinced.", "vo/npc/vortigaunt/vanswer01.wav")
Schema.voices.Add("Vortigaunt", "V1", "Ah'Glaa.", "vo/npc/vortigaunt/vortigese02.wav")
Schema.voices.Add("Vortigaunt", "V2", "Tahh.", "vo/npc/vortigaunt/vortigese03.wav")
Schema.voices.Add("Vortigaunt", "V3", "Dew'it.", "vo/npc/vortigaunt/vortigese04.wav")
Schema.voices.Add("Vortigaunt", "V4", "Langh.", "vo/npc/vortigaunt/vortigese05.wav")
Schema.voices.Add("Vortigaunt", "V5", "Gangh.", "vo/npc/vortigaunt/vortigese07.wav")
Schema.voices.Add("Vortigaunt", "V6", "Gulanga!", "vo/npc/vortigaunt/vortigese08.wav")
Schema.voices.Add("Vortigaunt", "V7", "Gallah'lung.", "vo/npc/vortigaunt/vortigese09.wav")
Schema.voices.Add("Vortigaunt", "V8", "Gerr, galling gerr a'la gam.", "vo/npc/vortigaunt/vortigese11.wav")
Schema.voices.Add("Vortigaunt", "V9", "Gerr, lung'gung. Jella'gerr.", "vo/npc/vortigaunt/vortigese12.wav")
Schema.voices.Add("Vortigaunt", "We Assure", "Likewise, we assure.", "vo/npc/vortigaunt/vanswer15.wav")
Schema.voices.Add("Vortigaunt", "We Can Spare", "That is all we can spare.", "vo/npc/vortigaunt/allwecanspare.wav")
Schema.voices.Add("Vortigaunt", "We Stay", "Here we stay.", "vo/npc/vortigaunt/herewestay.wav")
Schema.voices.Add("Vortigaunt", "We Will Help", "We will help you.", "vo/npc/vortigaunt/wewillhelp.wav")
Schema.voices.Add("Vortigaunt", "Where To", "Where to now? And to what end?", "vo/npc/vortigaunt/whereto.wav")
Schema.voices.Add("Vortigaunt", "Wish Right", "We wish you are right.", "vo/npc/vortigaunt/vanswer12.wav")
Schema.voices.Add("Vortigaunt", "Worthless", "Our life is worthless, unless spent on freedom.", "vo/npc/vortigaunt/worthless.wav")
Schema.voices.Add("Vortigaunt", "Yes", "Yessss.", "vo/npc/vortigaunt/yes.wav")
Schema.voices.Add("Vortigaunt", "Yes forward", "Yes, forward.", "vo/npc/vortigaunt/yesforward.wav")
Schema.voices.Add("Vortigaunt", "Energy empower", "It's energy empowers us.", "vo/npc/vortigaunt/energyempower.wav")
Schema.voices.Add("Vortigaunt", "Hold charge", "Hold still, we cannot charge you.", "vo/npc/vortigaunt/holdorcantcharge.wav")
Schema.voices.Add("Vortigaunt", "Honor follow", "To our honor, we follow you.", "vo/npc/vortigaunt/honorfollow.wav")
Schema.voices.Add("Vortigaunt", "Give over", "Give over your essence!", "vo/npc/vortigaunt/giveover.wav")
Schema.voices.Add("Vortigaunt", "Neuroprints", "So the neuroprints are true.", "vo/npc/vortigaunt/neuroprints.wav")
Schema.voices.Add("Vortigaunt", "Pass on", "Pass on!", "vo/npc/vortigaunt/passon.wav")
Schema.voices.Add("Vortigaunt", "If you move", "If you move, we cannot help you.", "vo/npc/vortigaunt/ifyoumove.wav")
Schema.voices.Add("Vortigaunt", "Hands occupied", "Our hands are occupied.", "vo/outland_01/intro/vort_rbed_letsgo01b.wav")
Schema.voices.Add("Vortigaunt", "Destroy obstacles", "Destroy all obstacles!", "vo/outland_01/intro/vort_rbed_letsgo01c.wav")
Schema.voices.Add("Vortigaunt", "Hasten", "We must hasten.", "vo/outland_01/intro/vort_rbed_letsgo04a.wav")
Schema.voices.Add("Vortigaunt", "V10", "Chaaann, Khooooo.. Par'Raaihh..", "vo/outland_01/intro/vort_rbed_vemotings01.wav")
Schema.voices.Add("Vortigaunt", "What harm", "What harm has come?", "vo/outland_01/intro/vort_rbed_whatharm.wav")
Schema.voices.Add("Vortigaunt", "Success", "Success!", "vo/outland_01/intro/vort_separation_success02.wav")
Schema.voices.Add("Vortigaunt", "Summon kin", "Let me summon my Kin.", "vo/outland_01/intro/vort_rbed_freeman05.wav")
Schema.voices.Add("Vortigaunt", "Hunters", "The Combine Hunters cause traumatic injury.", "vo/outland_02/junction/vort_junc_badlyinjured02.wav")
Schema.voices.Add("Vortigaunt", "Behold", "Behold!", "vo/outland_02/junction/vort_junc_behold.wav")
Schema.voices.Add("Vortigaunt", "Farewell", "Farewell.", "vo/outland_02/junction/vort_junc_bye01.wav")
Schema.voices.Add("Vortigaunt", "Farewell2", "Go safely.", "vo/outland_02/junction/vort_junc_bye02.wav")
Schema.voices.Add("Vortigaunt", "Farewell3", "Travel well.", "vo/outland_02/junction/vort_junc_bye03.wav")
Schema.voices.Add("Vortigaunt", "Exhausted", "We have exhausted their immediate number.", "vo/outland_02/junction/vort_junc_exhausted.wav")
Schema.voices.Add("Vortigaunt", "Killed Antlions", "We killed many Antlions.", "vo/outland_02/junction/vort_junc_killedmanyyet01.wav")
Schema.voices.Add("Vortigaunt", "Lie still", "Lie still.", "vo/outland_02/junction/vort_junc_liestill.wav")
Schema.voices.Add("Vortigaunt", "Matter of hours", "A matter of hours.", "vo/outland_02/junction/vort_junc_matterhours.wav")
Schema.voices.Add("Vortigaunt", "Moment longer", "A moment longer.", "vo/outland_02/junction/vort_junc_momentlonger.wav")
Schema.voices.Add("Vortigaunt", "Matter of urgency", "Now to the matter of urgency.", "vo/outland_02/junction/vort_junc_nextmatter.wav")
Schema.voices.Add("Vortigaunt", "No pulse", "No pulse!", "vo/outland_02/junction/vort_junc_nopulse01.wav")
Schema.voices.Add("Vortigaunt", "Quickening", "Yeess.. there is a quickening.", "vo/outland_02/junction/vort_junc_quicken.wav")
Schema.voices.Add("Vortigaunt", "Quiet them", "We shall quiet them.", "vo/outland_02/junction/vort_junc_quietthem.wav")
Schema.voices.Add("Vortigaunt", "Defend us", "Defend us!", "vo/outland_02/junction/vort_turret_defendus.wav")
Schema.voices.Add("Vortigaunt", "We need help", "We need help!", "vo/outland_02/junction/vort_turret_helpcall01.wav")
Schema.voices.Add("Vortigaunt", "Under attack", "We are under attack!", "vo/outland_02/junction/vort_turret_helpcall04.wav")
Schema.voices.Add("Vortigaunt", "Protect us", "Protect us!", "vo/outland_02/junction/vort_turret_protectus.wav")
Schema.voices.Add("Vortigaunt", "I descend", "I descend!", "vo/outland_03_04/tunnels/vort_04_elevator_descend_01.wav")
Schema.voices.Add("Vortigaunt", "Antlions", "Antlions.", "vo/outland_03_04/tunnels/vort_antlions_arrive_01.wav")
Schema.voices.Add("Vortigaunt", "Sad fate", "The sad fate of these others is our good fortune.", "vo/outland_03_04/tunnels/vort_breakweb02.wav")
Schema.voices.Add("Vortigaunt", "Agreed", "Agreed.", "vo/outland_03_04/tunnels/vort_extract_agreed.wav")
Schema.voices.Add("Vortigaunt", "Ah yes", "Ah yes.", "vo/outland_03_04/tunnels/vort_extract_ahyes.wav")
Schema.voices.Add("Vortigaunt", "bounty extract", "Ah excellent. A bounty of larve extract.", "vo/npc/vortigaunt/ifyoumove.wav")
Schema.voices.Add("Vortigaunt", "Take a moment", "This should only take a moment.", "vo/outland_03_04/tunnels/vort_extract_bounty02.wav")
Schema.voices.Add("Vortigaunt", "Finest quality", "Secretions of the finest quality.", "vo/outland_03_04/tunnels/vort_extract_finequality01.wav")
Schema.voices.Add("Vortigaunt", "Human is needed", "A human is needed.", "vo/outland_03_04/tunnels/vort_extract_humanmark.wav")
Schema.voices.Add("Vortigaunt", "Vortessence submersion", "This will necessitate deep submersion in the Vortessence.", "vo/outland_03_04/tunnels/vort_extract_injuriesdeep02.wav")
Schema.voices.Add("Vortigaunt", "Make Haste", "Make haste!", "vo/outland_03_04/tunnels/vort_extract_makehaste.wav")
Schema.voices.Add("Vortigaunt", "Secretion", "Miraculous secretion.", "vo/outland_03_04/tunnels/vort_extract_pharynx.wav")
Schema.voices.Add("Vortigaunt", "Extract2", "The Extraaaact!", "vo/outland_03_04/tunnels/vort_extract_theextract03.wav")
Schema.voices.Add("Vortigaunt", "Save yourself", "Save yourself!", "vo/outland_03_04/tunnels/vort_extract_tothelift02.wav")
Schema.voices.Add("Vortigaunt", "Require extract", "We require the Larval Extract.", "vo/outland_03_04/tunnels/vort_extract_werequire.wav")
Schema.voices.Add("Vortigaunt", "Now attack", "Now, attack!", "vo/outland_03_04/tunnels/vort_prone_nag_03.wav")
Schema.voices.Add("Vortigaunt", "Disabled", "I have disabled them.", "vo/outland_03_04/tunnels/vort_prone_nag_02.wav")
Schema.voices.Add("Vortigaunt", "Squish grub", "They are quiet pleasant underfoot, are they not?", "vo/outland_03_04/tunnels/vort_squishgrub01.wav")
Schema.voices.Add("Vortigaunt", "Far fetched", "Such a theory is hard far fetched.", "vo/outland_05/canyon/vort_canyon_farfetch.wav")
Schema.voices.Add("Vortigaunt", "Kill it", "If it tries to hinder our progress, we will have no choice but to kill it.", "vo/outland_05/canyon/vort_canyon_guardianrage02.wav")
Schema.voices.Add("Vortigaunt", "Urgent need", "They will understand our urgent need.", "vo/outland_05/canyon/vort_canyon_reside02.wav")
Schema.voices.Add("Vortigaunt", "Take shelter", "Take shelther near the repellant device!.", "vo/outland_05/canyon/vort_guard_alyxshelter01.wav")
Schema.voices.Add("Vortigaunt", "Guardian", "The Guardian.", "vo/outland_05/canyon/vort_guard_surfacesighting.wav")
Schema.voices.Add("Vortigaunt", "Gratitude", "Our bonds are of nature, and require no gratitude.", "vo/outland_06/bridge/vort_bridge_honored.wav")
Schema.voices.Add("Vortigaunt", "far fetched", "Such a theory is hard far fetched.", "vo/outland_05/canyon/vort_canyon_farfetch.wav")
Schema.voices.Add("Vortigaunt", "far fetched", "Such a theory is hard far fetched.", "vo/outland_05/canyon/vort_canyon_farfetch.wav")
Schema.voices.Add("Vortigaunt", "Our attention", "I feel a more urgent errand demand our attention.", "vo/outland_06/bridge/vort_bridge_hunt01.wav")
Schema.voices.Add("Vortigaunt", "Headcrabs", "Headcrabs have had their way with both parties.", "vo/outland_06/bridge/vort_bridge_nogoodend02.wav")
Schema.voices.Add("Vortigaunt", "Mounted gun", "This mounted gun may prove useful.", "vo/outland_06/bridge/vort_bridge_thismountgun.wav")
Schema.voices.Add("Vortigaunt", "True", "Regrettably True.", "vo/outland_11a/silo/vort_silo_regrettablytrue.wav")
Schema.voices.Add("Vortigaunt", "Chant", "*Chanting*", "npc/vort/ol02singlechant01.wav")
Schema.voices.Add("Vortigaunt", "Chant2", "*Chanting*", "npc/vort/ol02singlechant02.wav")
Schema.voices.Add("Vortigaunt", "Chant3", "*Chanting*", "npc/vort/ol02singlechant03.wav")
Schema.voices.Add("Vortigaunt", "vmono", "There is no distance between us. No false veils of time or space may intervene.", "vo/npc/vortigaunt/vmono_04.wav")
Schema.voices.Add("Vortigaunt", "vmono2", "For a brief time you joined us. You are one. Between the worlds.", "vo/npc/vortigaunt/vmono_07.wav")
Schema.voices.Add("Vortigaunt", "vmono3", "Communion of the vortessence. And that other: a deeper mystery. No deeper than the void itself.", "vo/npc/vortigaunt/vmono_08.wav")
Schema.voices.Add("Vortigaunt", "vmono4", "We cannot forget those whose cords you cut. Forgiveness is not ours to bestow.", "vo/npc/vortigaunt/vmono_09.wav")
Schema.voices.Add("Vortigaunt", "vmono5", "Unity of purpose, the shattering of common shackles, a single road we tread.", "vo/npc/vortigaunt/vmono_10.wav")
Schema.voices.Add("Vortigaunt", "vmono6", "Your song we sing and shall sing for eternity. No matter the consequences of this struggle.", "vo/npc/vortigaunt/vmono_11.wav")
Schema.voices.Add("Vortigaunt", "vmono7", "You have brought us grief and jubilation beyond measure.", "vo/npc/vortigaunt/vmono_12.wav")
Schema.voices.Add("Vortigaunt", "vmono8", "We are there still, in observance of your final stroke.", "vo/npc/vortigaunt/vmono_13.wav")
Schema.voices.Add("Vortigaunt", "vmono9", "That sharp spur of hope has not dulled to this day. For once the lesser master lay defeated, we knew the greater must also fall in time.", "vo/npc/vortigaunt/vmono_15.wav")
Schema.voices.Add("Vortigaunt", "vmono10", "With you besides us, a talisman of victory, the day of freedom draws nigh.", "vo/npc/vortigaunt/vmono_16.wav")
Schema.voices.Add("Vortigaunt", "vmono11", "Your bright face obscures your darker mask.", "vo/npc/vortigaunt/vmono_17.wav")
Schema.voices.Add("Vortigaunt", "vmono12", "We call you sib, although your mind and meaning are a mystery to us.", "vo/npc/vortigaunt/vmono_18.wav")
Schema.voices.Add("Vortigaunt", "vmono13", "Far distant eyes look out through yours.", "vo/npc/vortigaunt/vmono_19.wav")
Schema.voices.Add("Vortigaunt", "vmono14", "Something secret steers us both. We shall not name it.", "vo/npc/vortigaunt/vmono_20.wav")
Schema.voices.Add("Vortigaunt", "vmono15", "We have endured these chafing bonds for eons, yet a single moment of further servitude seems intolerable!", "vo/npc/vortigaunt/vmono_21.wav")
Schema.voices.Add("Vortigaunt", "vmono16", "How often have we slipped our yoke, only to find it choking us again.", "vo/npc/vortigaunt/vmono_22.wav")
Schema.voices.Add("Vortigaunt", "vmono17", "Let this war end in either total victory or our extinction. No further compromise shall we allow.", "vo/npc/vortigaunt/vmono_23.wav")
Schema.voices.Add("Vortigaunt", "vmono18", "We take our stand beside you, here, upon this miserable rock.", "vo/npc/vortigaunt/vmono_24.wav")
Schema.voices.Add("Vortigaunt", "vmono19", "The way ahead is dark for the moment.", "vo/npc/vortigaunt/vmono_25.wav")
Schema.voices.Add("Vortigaunt", "vmono20", "What seems to you a sacrifice is merely, to us, an oscillation. We do not fear the interval of darkness.", "vo/npc/vortigaunt/vmono_26.wav")
Schema.voices.Add("Vortigaunt", "vmono21", "We are a tapestry woven of vortessence. It is the same for you if only you would see it.", "vo/npc/vortigaunt/vmono_27.wav")
Schema.voices.Add("Vortigaunt", "vmono22", "How many are there in you? Whose hopes and dreams do you encompass?", "vo/npc/vortigaunt/vmono_28.wav")
Schema.voices.Add("Vortigaunt", "vmono23", "Could you but see the eyes inside your own, the minds in your mind, you would see how much we share.", "vo/npc/vortigaunt/vmono_29.wav")
Schema.voices.Add("Vortigaunt", "V11", "Kar'Raagh!", "vo/npc/vortigaunt/vort_attack21.wav")
Schema.voices.Add("Vortigaunt", "Excellent", "Excellent!", "vo/npc/vortigaunt/vort_excellent.wav")
Schema.voices.Add("Vortigaunt", "Excellent shooting", "Excellent shooting!", "vo/npc/vortigaunt/vort_excellentshooting.wav")
Schema.voices.Add("Vortigaunt", "Excellent Shot", "Excellent shot!", "vo/npc/vortigaunt/vort_excellentshot.wav")
Schema.voices.Add("Vortigaunt", "Exceptional", "Exceptional!", "vo/npc/vortigaunt/vort_exceptional.wav")
Schema.voices.Add("Vortigaunt", "Fight with us", "It is good that you now fight with us.", "vo/npc/vortigaunt/vort_goodfightwithus.wav")
Schema.voices.Add("Vortigaunt", "Work together", "It is good now that we work together.", "vo/npc/vortigaunt/vort_goodtogether.wav")
Schema.voices.Add("Vortigaunt", "Just so", "Just so.", "vo/npc/vortigaunt/vort_grp_agree01.wav")
Schema.voices.Add("Vortigaunt", "Agreed2", "Agreed.", "vo/npc/vortigaunt/vort_grp_agree02.wav")
Schema.voices.Add("Vortigaunt", "Hm", "Hmmmmmm...", "vo/npc/vortigaunt/vort_grp_agree03.wav")
Schema.voices.Add("Vortigaunt", "Ah", "Ahhhh...", "vo/npc/vortigaunt/vort_grp_agree04.wav")
Schema.voices.Add("Vortigaunt", "Yes", "Yeeess.", "vo/npc/vortigaunt/vort_grp_agree05.wav")
Schema.voices.Add("Vortigaunt", "Indeed", "Indeed.", "vo/npc/vortigaunt/vort_grp_agree06.wav")
Schema.voices.Add("Vortigaunt", "Well stated", "Well stated.", "vo/npc/vortigaunt/vort_grp_agree07.wav")
Schema.voices.Add("Vortigaunt", "Ah2", "Ahhhh...", "vo/npc/vortigaunt/vort_grp_greetings04.wav")
Schema.voices.Add("Vortigaunt", "Skills formidable", "Your skills are formidable.", "vo/npc/vortigaunt/vort_skillsformidable.wav")
Schema.voices.Add("Vortigaunt", "Yes", "Yeeess.", "vo/npc/vortigaunt/vort_grp_agree05.wav")

Schema.voices.AddClass("Vortigaunt", function(client)
	return client:IsVortigaunt()
end)
